name: Python application test

trigger:
- '*' 

pool:
  vmImage: 'ubuntu-latest'

strategy:
  maxParallel: 1


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.2'
    addToPath: true
  displayName: 'Set up Python 3.13.2'

- script: |
    make install
  displayName: 'Install dependencies'

- script: |
    make lint
  displayName: 'Lint with pylint'

- script: |
    make test
  displayName: 'Test with pytest'