trigger:
- main

pool: myPool

variables:
  appName: 'udp2'
  azureServiceConnectionId: 'myServiceConnection'
  environmentName: 'flask-ml-service'
  projectRoot: $(System.DefaultWorkingDirectory)
  repositoryName: 'ud-cloud-devops-p2'
  resourceGroup: 'Azuredevops'
  subscriptionId: '7de72e36-dc87-4e3f-aa67-6dacbc9993c6'
  webAppName: 'udacity_project2'
  vmName: 'myLinuxVM'
  vmUsername: 'azureuser'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool: myPool
    steps:    
    - script: |
        export PATH=$HOME/.local/bin:$PATH
        make install
        make lint
      workingDirectory: $(projectRoot)
      displayName: 'Run lint tests'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: myPool
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : flask-ml-service'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              appType: webApp